name: "chapter 08: Compile and Test fast feedback"
permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ "feature/*" ]
    paths:
    - 'frontend/**'
    - 'catalog/**'
    - 'ordering/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
